(function(global){
'use strict';

const planCache=new Map();
const CACHE_TTL=30000;
let availablePlans=[];
let originalCreatePI=null,originalCmpRowHTML=null,originalCmpDerived=null,originalRecompute=null;
const $=(s,r=document)=>r.querySelector(s);
const E=v=>typeof global.esc==='function'?global.esc(v):String(v??'');
const qty=v=>Math.max(0,Math.trunc(Number(v)||0));
const apiCall=(u,m='GET',b=null)=>global.api(u,m,b);
const statusText=s=>({open:'待采购',partial:'部分转PI',completed:'已全部转PI',closed:'已关闭'}[s]||s||'—');
const statusClass=s=>s==='completed'?'status-completed':s==='partial'?'status-pending':s==='closed'?'status-draft':'status-approved';
function cacheKey(){return [$('#po-fs')?.value||'',$('#po-fb')?.value||'',$('#po-fc')?.value||'',$('#po-fk')?.value||''].join('|');}
function clearCaches(){planCache.clear();availablePlans=[];try{if(global.AppStore)global.AppStore.onMutation('PUT','/api/purchase-orders/po-plan',{});}catch(_e){}}
function ensureCss(){if($('#po-plan-css'))return;const s=document.createElement('style');s.id='po-plan-css';s.textContent=`.po-plan-summary{display:flex;gap:18px;align-items:center}.po-plan-num{font-variant-numeric:tabular-nums;font-weight:650}.po-plan-remain{color:#1677ff;font-weight:700}.po-plan-used{color:#6e6e73}.po-plan-editor{border:1px solid #e7e7ea;border-radius:14px;overflow:hidden}.po-plan-editor table{width:100%;border-collapse:collapse}.po-plan-editor th{font-size:12px;color:#6e6e73;background:#f7f8fa;padding:9px}.po-plan-editor td{padding:8px;border-top:1px solid #eee}.po-plan-editor input{height:34px;border:1px solid #d8dadd;border-radius:8px;padding:0 9px}.po-plan-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}.po-plan-card{background:#f7f8fa;border-radius:12px;padding:12px}.po-plan-card span{font-size:11px;color:#86868b}.po-plan-card b{display:block;font-size:21px;margin-top:4px}.po-plan-hint{font-size:12px;color:#6e6e73;background:#f5f7fb;border-radius:10px;padding:9px 11px;margin:10px 0}.po-plan-pi-note{font-size:11px;color:#6e6e73;margin-top:4px}`;document.head.appendChild(s);}

function renderPOPlan(){
  ensureCss();
  const c=$('#content-inner');if(!c)return;
  c.innerHTML=`<div id="flash-container"></div><div class="filter-bar"><div class="filter-form"><div class="filter-group"><label>状态</label><select id="po-fs"><option value="">全部</option><option value="open">待采购</option><option value="partial">部分转PI</option><option value="completed">已全部转PI</option><option value="closed">已关闭</option></select></div><div class="filter-group"><label>品牌</label><input id="po-fb" placeholder="全部品牌"></div><div class="filter-group"><label>国家</label><input id="po-fc" placeholder="全部国家"></div><div class="filter-group"><label>关键词</label><input id="po-fk" placeholder="PO号 / 供应商"></div><div class="filter-actions"><button class="btn btn-primary btn-sm" id="po-plan-search">搜索</button>${global.hasPermission&&global.hasPermission('po_create')?'<button class="btn btn-primary btn-sm" id="po-plan-new">➕ 新建PO</button>':''}</div></div></div><div class="table-section"><div class="table-section-title"><div class="table-section-title-left">🛒 PO采购计划</div><div style="font-size:12px;color:#86868b">PO=动态采购计划 · PI=实际采购确认</div></div><div id="po-table"><div class="empty-state"><div class="empty-icon">⏳</div>加载中…</div></div></div>`;
  $('#po-plan-search').onclick=()=>loadPOPlan(false);$('#po-fk').onkeypress=e=>{if(e.key==='Enter')loadPOPlan(false)};if($('#po-plan-new'))$('#po-plan-new').onclick=createPOPlan;
  loadPOPlan(true);
}
async function loadPOPlan(useCache){
  const key=cacheKey(),el=$('#po-table');if(!el)return;
  const hit=planCache.get(key);if(useCache&&hit&&Date.now()-hit.at<CACHE_TTL){drawPOPlan(hit.data);fetchPOPlan(key,true);return;}
  await fetchPOPlan(key,false);
}
async function fetchPOPlan(key,background){
  try{
    const q=new URLSearchParams(),s=$('#po-fs')?.value||'',b=$('#po-fb')?.value.trim()||'',c=$('#po-fc')?.value.trim()||'',k=$('#po-fk')?.value.trim()||'';
    if(s)q.set('status',s);if(b)q.set('brand',b);if(c)q.set('country',c);if(k)q.set('keyword',k);
    const data=await apiCall('/api/po-plans?'+q.toString());planCache.set(key,{at:Date.now(),data});if(key===cacheKey())drawPOPlan(data);
  }catch(e){if(!background&&$('#po-table'))$('#po-table').innerHTML='<div class="empty-state">'+E(e.message)+'</div>';}
}
function drawPOPlan(data){
  const el=$('#po-table');if(!el)return;
  if(!data.length){el.innerHTML='<div class="empty-state"><div class="empty-icon">🛒</div>暂无PO采购计划</div>';return;}
  el.innerHTML=`<div class="table-container" style="box-shadow:none;border-radius:0"><table class="data-table"><thead><tr><th>PO号</th><th>供应商</th><th>品牌</th><th>国家</th><th>仓库</th><th>PO日期</th><th>明细</th><th>计划数量</th><th>已转PI</th><th>剩余可转</th><th>状态</th><th>操作</th></tr></thead><tbody>${data.map(p=>`<tr class="clickable-detail-row" data-id="${E(p.id)}"><td class="cell-id"><span class="link-text">${E(p.po_no)}</span></td><td>${E(p.supplier_name)}</td><td>${E(p.brand)}</td><td>${E(p.country)}</td><td>${E(p.target_warehouse)}</td><td class="cell-date">${global.fmtDate?global.fmtDate(p.po_date):E(p.po_date)}</td><td class="text-center">${qty(p.item_count)}</td><td class="text-right po-plan-num">${qty(p.planned_qty)}</td><td class="text-right po-plan-used">${qty(p.transferred_qty)}</td><td class="text-right po-plan-remain">${qty(p.remaining_qty)}</td><td><span class="status-badge ${statusClass(p.plan_status)}">${statusText(p.plan_status)}</span></td><td class="cell-actions"><button class="action-btn pp-view">👁️</button>${global.hasPermission&&global.hasPermission('po_create')&&p.plan_status!=='closed'?'<button class="action-btn pp-edit" title="编辑计划数量">✏️</button><button class="action-btn pp-close" title="关闭PO">关闭</button>':''}${global.hasPermission&&global.hasPermission('po_create')&&qty(p.transferred_qty)===0?'<button class="action-btn pp-del" style="color:#d4380d" title="删除未使用PO">删除</button>':''}</td></tr>`).join('')}</tbody></table></div>`;
  el.querySelectorAll('tr[data-id]').forEach(tr=>{const id=tr.dataset.id;tr.onclick=e=>{if(e.target.closest('button'))return;viewPOPlan(id)};tr.querySelector('.pp-view').onclick=()=>viewPOPlan(id);tr.querySelector('.pp-edit')?.addEventListener('click',()=>editPOPlan(id));tr.querySelector('.pp-close')?.addEventListener('click',()=>closePOPlan(id));tr.querySelector('.pp-del')?.addEventListener('click',()=>deletePOPlan(id));});
}
async function createPOPlan(){
  global.openModal('新建PO采购计划','<div style="padding:40px;text-align:center">⏳ 加载中…</div>');
  try{
    const m=typeof global._getMaster==='function'?await global._getMaster(['suppliers','countries','brands']):{suppliers:await apiCall('/api/suppliers'),countries:[],brands:[]};
    if(!$('#modal-overlay')?.classList.contains('show'))return;
    const countries=(m.countries||[]).filter(x=>!x.status||x.status==='active');
    global.openModal('新建PO采购计划',`<div class="form-card" style="box-shadow:none;padding:0"><div class="po-plan-hint">PO无需审批，只维护采购计划数量；真正采购数量和价格在PI确认。</div><div class="form-grid"><div class="form-group"><label>供应商 *</label><select id="pp-sup">${(m.suppliers||[]).map(x=>`<option value="${E(x.id)}" data-name="${E(x.name)}">${E(x.name)}</option>`).join('')}</select></div><div class="form-group"><label>品牌 *</label><select id="pp-brand"><option value="">请选择</option>${(m.brands||[]).map(x=>`<option>${E(x)}</option>`).join('')}</select></div><div class="form-group"><label>国家 *</label><select id="pp-country"><option value="">请选择</option>${countries.map(x=>`<option>${E(x.name)}</option>`).join('')}</select></div><div class="form-group"><label>仓库 *</label><input id="pp-wh"></div><div class="form-group"><label>PO日期</label><input type="date" id="pp-date" value="${new Date().toISOString().slice(0,10)}"></div><div class="form-group"><label>币种</label><select id="pp-cur"><option>RMB</option><option>USD</option></select></div></div><h4 style="margin:16px 0 8px">采购计划明细 <button class="btn btn-secondary btn-sm" id="pp-add">➕ 添加SKU</button></h4><div id="pp-create-items" class="po-plan-editor"></div></div>`,`<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" id="pp-save-new">创建计划</button>`);
    global._ppCreateRows=[{sku:'',qty:1}];renderCreateRows();$('#pp-add').onclick=()=>{global._ppCreateRows.push({sku:'',qty:1});renderCreateRows()};$('#pp-save-new').onclick=saveNewPOPlan;
  }catch(e){global.showToast(e.message,'danger')}
}
function renderCreateRows(){const rows=global._ppCreateRows||[];$('#pp-create-items').innerHTML=`<table><thead><tr><th>SKU</th><th>计划数量</th><th></th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><input id="pp-c-s-${i}" value="${E(r.sku)}" style="width:100%"></td><td><input id="pp-c-q-${i}" type="number" min="1" step="1" value="${qty(r.qty)||1}" style="width:130px"></td><td><button class="btn btn-danger btn-sm" data-rm="${i}">🗑️</button></td></tr>`).join('')}</tbody></table>`;$('#pp-create-items').querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{global._ppCreateRows.splice(Number(b.dataset.rm),1);renderCreateRows()});}
async function saveNewPOPlan(){
  const rows=(global._ppCreateRows||[]).map((r,i)=>({sku_code:$('#pp-c-s-'+i)?.value.trim()||'',po_qty:Number($('#pp-c-q-'+i)?.value||0)})).filter(x=>x.sku_code);const sup=$('#pp-sup'),body={supplier_id:sup.value,supplier_name:sup.options[sup.selectedIndex]?.dataset.name||'',brand:$('#pp-brand').value,country:$('#pp-country').value,target_warehouse:$('#pp-wh').value.trim(),po_date:$('#pp-date').value,currency:$('#pp-cur').value,items:rows};
  try{await apiCall('/api/po-plans','POST',body);clearCaches();global.closeModal();global.showToast('PO采购计划已创建，无需审批','success');loadPOPlan(false);}catch(e){global.showToast(e.message,'danger')}
}
async function viewPOPlan(id){try{const p=await apiCall('/api/po-plans/'+id);global.openModal('PO采购计划 - '+E(p.po_no),`<div class="detail-card" style="box-shadow:none;padding:0"><div class="detail-section"><h3>计划信息</h3><div class="detail-grid">${[['供应商',p.supplier_name],['品牌',p.brand],['国家',p.country],['仓库',p.target_warehouse],['PO日期',p.po_date],['状态',statusText(p.plan_status)]].map(x=>`<div class="detail-item"><span class="detail-label">${x[0]}</span><span class="detail-value">${E(x[1]||'—')}</span></div>`).join('')}</div><div class="po-plan-cards"><div class="po-plan-card"><span>计划数量</span><b>${qty(p.planned_qty)}</b></div><div class="po-plan-card"><span>已转PI</span><b>${qty(p.transferred_qty)}</b></div><div class="po-plan-card"><span>剩余可转</span><b class="po-plan-remain">${qty(p.remaining_qty)}</b></div></div></div><div class="detail-section"><h3>SKU计划</h3><div class="table-container"><table class="data-table"><thead><tr><th>SKU</th><th>计划数量</th><th>已转PI</th><th>剩余可转</th></tr></thead><tbody>${p.items.map(i=>`<tr><td class="cell-id">${E(i.sku_code)}</td><td class="text-right">${qty(i.planned_qty)}</td><td class="text-right">${qty(i.transferred_qty)}</td><td class="text-right po-plan-remain">${qty(i.remaining_qty)}</td></tr>`).join('')}</tbody></table></div></div></div>`,`${global.hasPermission&&global.hasPermission('po_create')&&p.plan_status!=='closed'?`<button class="btn btn-primary" id="pp-detail-edit">编辑数量</button>`:''}<button class="btn btn-secondary" onclick="closeModal()">关闭</button>`);$('#pp-detail-edit')?.addEventListener('click',()=>editPOPlan(id));}catch(e){global.showToast(e.message,'danger')}}
async function editPOPlan(id){try{const p=await apiCall('/api/po-plans/'+id);global._ppEdit=p;global.openModal('编辑PO计划 - '+E(p.po_no),`<div class="po-plan-hint">数量可随时调整，但不能低于已经转入PI的数量；已转PI的SKU不能删除或更换。</div><div class="form-grid"><div class="form-group"><label>品牌</label><input id="pp-e-brand" value="${E(p.brand)}"></div><div class="form-group"><label>国家</label><input id="pp-e-country" value="${E(p.country)}"></div><div class="form-group"><label>仓库</label><input id="pp-e-wh" value="${E(p.target_warehouse)}"></div><div class="form-group"><label>预计交期</label><input type="date" id="pp-e-del" value="${E(p.expected_delivery||'')}"></div></div><h4 style="margin:16px 0 8px">计划明细 <button class="btn btn-secondary btn-sm" id="pp-e-add">➕ 添加SKU</button></h4><div id="pp-edit-items" class="po-plan-editor"></div>`,`<button class="btn btn-secondary" onclick="closeModal()">取消</button><button class="btn btn-primary" id="pp-e-save">保存计划</button>`);renderEditRows();$('#pp-e-add').onclick=()=>{global._ppEdit.items.push({id:'',sku_code:'',planned_qty:1,transferred_qty:0,remaining_qty:1});renderEditRows()};$('#pp-e-save').onclick=savePOPlanEdit;}catch(e){global.showToast(e.message,'danger')}}
function renderEditRows(){const p=global._ppEdit,rows=p.items||[];$('#pp-edit-items').innerHTML=`<table><thead><tr><th>SKU</th><th>计划数量</th><th>已转PI</th><th>剩余可转</th><th></th></tr></thead><tbody>${rows.map((r,i)=>{const used=qty(r.transferred_qty),planned=qty(r.planned_qty),rem=Math.max(0,planned-used);return `<tr><td><input id="pp-e-s-${i}" value="${E(r.sku_code)}" ${used?'readonly':''} style="width:100%"></td><td><input id="pp-e-q-${i}" type="number" min="${Math.max(1,used)}" step="1" value="${planned||Math.max(1,used)}" style="width:120px" data-i="${i}"></td><td class="text-right po-plan-used">${used}</td><td id="pp-e-r-${i}" class="text-right po-plan-remain">${rem}</td><td>${used?'<span style="font-size:11px;color:#86868b">已使用</span>':`<button class="btn btn-danger btn-sm" data-rm="${i}">🗑️</button>`}</td></tr>`}).join('')}</tbody></table>`;$('#pp-edit-items').querySelectorAll('input[data-i]').forEach(x=>x.oninput=()=>{const i=Number(x.dataset.i),used=qty(rows[i].transferred_qty),v=qty(x.value);$('#pp-e-r-'+i).textContent=Math.max(0,v-used)});$('#pp-edit-items').querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{rows.splice(Number(b.dataset.rm),1);renderEditRows()});}
async function savePOPlanEdit(){const p=global._ppEdit,items=(p.items||[]).map((r,i)=>({id:r.id||'',sku_code:$('#pp-e-s-'+i)?.value.trim()||'',po_qty:Number($('#pp-e-q-'+i)?.value||0),remark:r.remark||''}));try{await apiCall('/api/po-plans/'+p.id,'PUT',{brand:$('#pp-e-brand').value.trim(),country:$('#pp-e-country').value.trim(),target_warehouse:$('#pp-e-wh').value.trim(),expected_delivery:$('#pp-e-del').value,items});clearCaches();global.closeModal();global.showToast('PO计划已更新','success');loadPOPlan(false);}catch(e){global.showToast(e.message,'danger')}}
async function closePOPlan(id){if(!global.confirm('关闭后该PO不再用于新PI，历史PI不受影响。确认关闭？'))return;try{await apiCall('/api/po-plans/'+id+'/close','POST',{});clearCaches();global.showToast('PO已关闭','success');loadPOPlan(false);}catch(e){global.showToast(e.message,'danger')}}
async function deletePOPlan(id){if(!global.confirm('仅未被PI使用的PO可以删除。确认删除？'))return;try{await apiCall('/api/po-plans/'+id,'DELETE');clearCaches();global.showToast('PO已删除','success');loadPOPlan(false);}catch(e){global.showToast(e.message,'danger')}}

function installPIIntegration(){
  const rawApi=global.api;if(typeof rawApi==='function'&&!rawApi.__poPlanCapture){const wrapped=async function(url){const out=await rawApi.apply(this,arguments);if(String(url||'').split('?')[0]==='/api/po-plans/available'&&Array.isArray(out))availablePlans=out;return out;};wrapped.__poPlanCapture=true;global.api=wrapped;}
  originalCreatePI=global.createPI;originalCmpRowHTML=global.cmpRowHTML;originalCmpDerived=global.cmpDerived;originalRecompute=global.recomputeCmpFooter;
  if(typeof originalCreatePI==='function')global.createPI=async function(){await originalCreatePI.apply(this,arguments);bindPIPlanFilters();};
  if(typeof originalCmpDerived==='function')global.cmpDerived=function(r){if(r&&r.poRemaining!=null)return originalCmpDerived({...r,poQty:r.poRemaining});return originalCmpDerived(r);};
  if(typeof originalCmpRowHTML==='function')global.cmpRowHTML=function(idx,r){if(!r||r.poRemaining==null)return originalCmpRowHTML(idx,r);return `<tr data-idx="${idx}"><td><input type="text" value="${E(r.sku)}" id="pi-rsk-${idx}" readonly></td><td style="color:var(--text-muted)" title="原计划 ${qty(r.poQty)} / 已转 ${qty(r.poTransferred)}">${qty(r.poRemaining)}</td><td><input type="number" min="0" max="${qty(r.poRemaining)}" value="${r.piQty||0}" id="pi-rq-${idx}" oninput="updCmpRow(${idx})"></td><td style="color:var(--text-muted)">${global.fmtMoney(r.poPrice||0)}</td><td><input type="number" step="0.01" value="${r.piPrice||0}" id="pi-rp-${idx}" oninput="updCmpRow(${idx})"></td><td><input type="number" step="0.01" value="${r.piDisc||0}" id="pi-rd-${idx}" oninput="updCmpRow(${idx})"></td><td id="pi-ramt-${idx}">0.00</td><td id="pi-rqd-${idx}">0</td><td id="pi-rpd-${idx}">0</td><td><button class="btn btn-danger btn-sm" onclick="delCmpRow(${idx})">🗑️</button></td></tr>`;};
  global.loadPOForPI=loadPlanForPI;
}
function bindPIPlanFilters(){const po=$('#npi-po'),country=$('#npi-country'),brand=$('#npi-brand');if(!po)return;const label=po.closest('.form-group');if(label&&!label.querySelector('.po-plan-pi-note'))label.insertAdjacentHTML('beforeend','<div class="po-plan-pi-note">先选国家/品牌，可快速筛选仍有剩余数量的PO</div>');const filter=()=>{const c=country?.value||'',b=brand?.value||'',cur=po.value;po.innerHTML='<option value="">无关联</option>'+availablePlans.filter(p=>(!c||p.country===c)&&(!b||p.brand===b)&&qty(p.remaining_qty)>0).map(p=>`<option value="${E(p.id)}">${E(p.po_no)} · ${E(p.brand)} · ${E(p.country)} · 剩余 ${qty(p.remaining_qty)}</option>`).join('');if([...po.options].some(o=>o.value===cur))po.value=cur;};country?.addEventListener('change',filter);brand?.addEventListener('change',filter);filter();const heads=$('#pi-items-table')?.querySelectorAll('thead th');if(heads&&heads[1])heads[1].textContent='PO剩余可转';}
async function loadPlanForPI(){const poId=$('#npi-po')?.value;global._poRef=null;const cur=$('#npi-cur'),country=$('#npi-country'),wh=$('#npi-wh'),brand=$('#npi-brand');if(!poId){if(cur)cur.disabled=false;if(typeof global.setPICountryWarehouseEditable==='function')global.setPICountryWarehouseEditable(true);if(brand)brand.disabled=false;if(country)country.disabled=false;if(wh)wh.disabled=false;global._piRows=[];global.renderCmpTable();return;}try{const po=await apiCall('/api/po-plans/'+poId);const sup=$('#npi-sup');let sid=po.supplier_id;if(sup&&sid&&![...sup.options].some(o=>o.value===sid)){const x=[...sup.options].find(o=>o.dataset.name===po.supplier_name);if(x)sid=x.value;}if(sup)sup.value=sid||'';if(typeof global.onPISupplierChange==='function')global.onPISupplierChange();if(cur){cur.value=po.currency;cur.disabled=true;}if(country){country.value=po.country||'';country.disabled=true;}if(wh){if(typeof global.populatePIWarehouse==='function')await global.populatePIWarehouse(po.country||'');wh.value=po.target_warehouse||'';wh.disabled=true;}if(brand){brand.value=po.brand||'';brand.disabled=true;}global._poRef=po.items||[];const extra=(global._piRows||[]).filter(r=>!r.fromPO);global._piRows=(po.items||[]).filter(it=>qty(it.remaining_qty)>0).map(it=>({sku:it.sku_code||'',poQty:qty(it.po_qty),poRemaining:qty(it.remaining_qty),poTransferred:qty(it.transferred_pi_qty),poPrice:Number(it.unit_price)||0,piQty:0,piPrice:0,piDisc:0,fromPO:true})).concat(extra);global.renderCmpTable();const heads=$('#pi-items-table')?.querySelectorAll('thead th');if(heads&&heads[1])heads[1].textContent='PO剩余可转';}catch(e){global.showToast(e.message,'danger')}}

function boot(){ensureCss();global.renderPO=renderPOPlan;global.loadPO=loadPOPlan;global.viewPO=viewPOPlan;global.createPO=createPOPlan;installPIIntegration();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window);
