'use strict';
module.exports=function installQuotationManagement(deps){
  const {app,query,queryOne,run,transaction,genId,asyncHandler,requireApiPermission}=deps;
  const BRAND_CCY=Object.freeze({Netac:'USD',Redragon:'RMB',BOYA:'RMB',Joypeer:'RMB'});
  run("CREATE TABLE IF NOT EXISTS quotation_prices (id TEXT PRIMARY KEY, sku_code TEXT NOT NULL, brand TEXT NOT NULL, product_type TEXT NOT NULL, quote_price NUMERIC NOT NULL, currency TEXT NOT NULL, quote_date TEXT NOT NULL, remark TEXT DEFAULT '', import_batch_id TEXT, created_at TEXT, updated_at TEXT)");
  run('CREATE UNIQUE INDEX IF NOT EXISTS uq_quotation_prices_sku_brand_date ON quotation_prices (sku_code,brand,quote_date)');
  run('CREATE INDEX IF NOT EXISTS idx_quotation_prices_brand_sku_date ON quotation_prices (brand,sku_code,quote_date)');
  run('CREATE INDEX IF NOT EXISTS idx_quotation_prices_brand_date ON quotation_prices (brand,quote_date)');
  const pct=(a,b)=>{a=Number(a);b=Number(b);return Number.isFinite(a)&&Number.isFinite(b)&&b!==0?Math.round(((a-b)/b)*10000)/100:null;};
  function purchaseBaselines(pairs){
    const uniq=[...new Map((pairs||[]).filter(p=>p&&p.sku&&p.brand).map(p=>[p.brand+'|'+p.sku,p])).values()],out=new Map();if(!uniq.length)return out;
    const skus=[...new Set(uniq.map(p=>p.sku))],ph=skus.map(()=>'?').join(',');
    const rows=query(`SELECT ci.id AS ci_id,ci.ci_no,ci.brand,ci.currency,COALESCE(NULLIF(ci.actual_ship_date,''),NULLIF(ci.ci_date,''),ci.created_at) AS purchase_date,cii.sku_code,cii.unit_price FROM commercial_invoice_items cii JOIN commercial_invoices ci ON ci.id=cii.ci_id WHERE cii.sku_code IN (${ph}) AND cii.unit_price IS NOT NULL ORDER BY cii.sku_code,ci.brand,COALESCE(NULLIF(ci.actual_ship_date,''),NULLIF(ci.ci_date,''),ci.created_at) DESC,ci.created_at DESC,ci.id DESC`,skus).rows;
    const wanted=new Set(uniq.map(p=>p.brand+'|'+p.sku)),picked=new Map();
    for(const r of rows){const k=(r.brand||'')+'|'+(r.sku_code||'');if(!wanted.has(k))continue;let x=picked.get(k);if(!x){x={ci_id:r.ci_id,ci_no:r.ci_no,currency:r.currency,purchase_date:r.purchase_date,prices:new Set()};picked.set(k,x);}if(x.ci_id===r.ci_id)x.prices.add(String(r.unit_price));}
    for(const[k,x]of picked){const v=[...x.prices].map(Number).filter(Number.isFinite);out.set(k,{ci_id:x.ci_id,ci_no:x.ci_no,currency:x.currency,purchase_date:x.purchase_date,unit_price:v.length===1?v[0]:null,status:v.length===1?'exact':'ambiguous'});}return out;
  }
  function buildSummary(req){
    const brand=String(req.query.brand||'').trim(),type=String(req.query.product_type||'').trim(),kw=String(req.query.keyword||'').trim().toLowerCase(),from=String(req.query.date_from||'').trim(),to=String(req.query.date_to||'').trim();let sql='SELECT * FROM quotation_prices WHERE 1=1',ps=[];
    if(brand){sql+=' AND brand=?';ps.push(brand);}if(type){sql+=' AND product_type=?';ps.push(type);}if(kw){sql+=' AND (LOWER(sku_code) LIKE ? OR LOWER(product_type) LIKE ? OR LOWER(brand) LIKE ?)';const q='%'+kw+'%';ps.push(q,q,q);}if(from){sql+=' AND quote_date>=?';ps.push(from);}if(to){sql+=' AND quote_date<=?';ps.push(to);}sql+=' ORDER BY brand,sku_code,quote_date DESC,created_at DESC';
    const history=query(sql,ps).rows,by=new Map();for(const r of history){const k=r.brand+'|'+r.sku_code;if(!by.has(k))by.set(k,[]);by.get(k).push(r);}const pmap=purchaseBaselines([...by.values()].map(a=>({brand:a[0].brand,sku:a[0].sku_code}))),rows=[];
    for(const[k,a]of by){const l=a[0],prev=a[1]||null,p=pmap.get(k)||null,same=!!p&&String(p.currency||'').toUpperCase()===String(l.currency||'').toUpperCase();rows.push({sku_code:l.sku_code,brand:l.brand,product_type:l.product_type,latest_price:Number(l.quote_price),currency:l.currency,latest_date:l.quote_date,previous_price:prev?Number(prev.quote_price):null,vs_previous_pct:prev?pct(l.quote_price,prev.quote_price):null,last_purchase_price:same&&p.status==='exact'?p.unit_price:null,last_purchase_currency:p?p.currency:null,last_purchase_date:p?p.purchase_date:null,last_purchase_ci_no:p?p.ci_no:null,purchase_status:p?(same?p.status:'currency_mismatch'):'missing',vs_purchase_pct:same&&p.status==='exact'?pct(l.quote_price,p.unit_price):null,history_count:a.length});}
    rows.sort((a,b)=>String(a.sku_code).localeCompare(String(b.sku_code)));
    const actual=query("SELECT DISTINCT brand FROM quotation_prices WHERE brand IS NOT NULL AND brand<>'' ORDER BY brand").rows.map(r=>r.brand),brands=[...new Set(['Netac','Redragon','BOYA','Joypeer',...actual])];let tsql="SELECT DISTINCT product_type FROM quotation_prices WHERE product_type IS NOT NULL AND product_type<>''",tps=[];if(brand){tsql+=' AND brand=?';tps.push(brand);}tsql+=' ORDER BY product_type';const productTypes=query(tsql,tps).rows.map(r=>r.product_type);
    const changes=rows.map(r=>r.vs_previous_pct).filter(v=>v!==null),pchanges=rows.map(r=>r.vs_purchase_pct).filter(v=>v!==null),types={};rows.forEach(r=>types[r.product_type||'未分类']=(types[r.product_type||'未分类']||0)+1);const trendMap=new Map();for(const h of history){if(!trendMap.has(h.quote_date))trendMap.set(h.quote_date,[]);trendMap.get(h.quote_date).push(Number(h.quote_price));}const trend=[...trendMap].sort((a,b)=>String(a[0]).localeCompare(String(b[0]))).slice(-24).map(([date,v])=>({date,avg_price:v.reduce((s,n)=>s+n,0)/v.length,count:v.length}));const month=new Date().toISOString().slice(0,7);
    return{brands,product_types:productTypes,rows,report:{brand:brand||null,currency:brand?(BRAND_CCY[brand]||(rows[0]&&rows[0].currency)||''):'',sku_count:rows.length,history_count:history.length,updated_this_month:rows.filter(r=>String(r.latest_date||'').slice(0,7)===month).length,up_count:changes.filter(v=>v>0).length,down_count:changes.filter(v=>v<0).length,avg_change_pct:changes.length?Math.round(changes.reduce((s,v)=>s+v,0)/changes.length*100)/100:null,above_purchase_count:pchanges.filter(v=>v>0).length,below_purchase_count:pchanges.filter(v=>v<0).length,product_types:types,top_movers:rows.filter(r=>r.vs_previous_pct!==null).sort((a,b)=>Math.abs(b.vs_previous_pct)-Math.abs(a.vs_previous_pct)).slice(0,5),top_purchase_gaps:rows.filter(r=>r.vs_purchase_pct!==null).sort((a,b)=>Math.abs(b.vs_purchase_pct)-Math.abs(a.vs_purchase_pct)).slice(0,5),trend}};
  }
  app.get('/api/quotation-management/summary',requireApiPermission('cost_view'),asyncHandler((req,res)=>{try{res.json(buildSummary(req));}catch(e){res.status(500).json({error:e.message});}}));
  app.get('/api/quotation-management/sku/:sku',requireApiPermission('cost_view'),asyncHandler((req,res)=>{try{const sku=String(req.params.sku||'').trim(),brand=String(req.query.brand||'').trim();if(!sku||!brand)return res.status(400).json({error:'缺少 SKU 或品牌'});const h=query('SELECT * FROM quotation_prices WHERE sku_code=? AND brand=? ORDER BY quote_date DESC,created_at DESC',[sku,brand]).rows,p=purchaseBaselines([{sku,brand}]).get(brand+'|'+sku)||null;res.json({sku_code:sku,brand,purchase:p,history:h.map((r,i)=>{const prev=h[i+1],same=!!p&&String(p.currency||'').toUpperCase()===String(r.currency||'').toUpperCase();return{...r,quote_price:Number(r.quote_price),vs_previous_pct:prev?pct(r.quote_price,prev.quote_price):null,vs_purchase_pct:same&&p.status==='exact'?pct(r.quote_price,p.unit_price):null};})});}catch(e){res.status(500).json({error:e.message});}}));
  app.post('/api/quotation-management/import',requireApiPermission('cost_view'),asyncHandler((req,res)=>{try{const input=Array.isArray((req.body||{}).rows)?req.body.rows:[],mode=(req.body||{}).duplicate_mode==='overwrite'?'overwrite':'skip';if(!input.length)return res.status(400).json({error:'导入数据不能为空'});if(input.length>5000)return res.status(400).json({error:'单次最多导入5000行'});const rows=[],errors=[];input.forEach((r,i)=>{const sku=String(r.sku_code||r.SKU||r['SKU']||'').trim(),brand=String(r.brand||r['品牌']||'').trim(),product_type=String(r.product_type||r['产品类型']||'').trim(),quote_price=Number(r.quote_price??r['FOB价格']??r['报价价格']??r['报价']),currency=String(r.currency||r['币种']||BRAND_CCY[brand]||'').trim().toUpperCase(),quote_date=String(r.quote_date||r['报价日期']||'').trim().slice(0,10),remark=String(r.remark||r['备注']||'').trim(),expected=BRAND_CCY[brand];if(!sku||!brand||!product_type||!(quote_price>0)||!/^\d{4}-\d{2}-\d{2}$/.test(quote_date)||!currency)errors.push({row:i+2,reason:'必填字段缺失或格式错误'});else if(expected&&currency!==expected)errors.push({row:i+2,reason:brand+' 默认币种应为 '+expected});else rows.push({sku,brand,product_type,quote_price,currency,quote_date,remark});});if(errors.length)return res.status(400).json({error:'导入校验失败',errors});let inserted=0,updated=0,skipped=0;const batch=genId('quoteimp'),now=new Date().toISOString();transaction(()=>{for(const r of rows){const old=queryOne('SELECT id FROM quotation_prices WHERE sku_code=? AND brand=? AND quote_date=?',[r.sku,r.brand,r.quote_date]);if(old){if(mode==='overwrite'){run('UPDATE quotation_prices SET product_type=?,quote_price=?,currency=?,remark=?,import_batch_id=?,updated_at=? WHERE id=?',[r.product_type,r.quote_price,r.currency,r.remark,batch,now,old.id]);updated++;}else skipped++;}else{run('INSERT INTO quotation_prices (id,sku_code,brand,product_type,quote_price,currency,quote_date,remark,import_batch_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[genId('quote'),r.sku,r.brand,r.product_type,r.quote_price,r.currency,r.quote_date,r.remark,batch,now,now]);inserted++;}}});res.json({success:true,inserted,updated,skipped,total:rows.length,import_batch_id:batch});}catch(e){res.status(500).json({error:e.message});}}));
};
