'use strict';
const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.join(__dirname,'..');
const router=fs.readFileSync(path.join(root,'src','http-router.js'),'utf8');
const server=fs.readFileSync(path.join(root,'src','standalone-server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'web','index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'web','app.js'),'utf8');
const schema=fs.readFileSync(path.join(root,'schema-brand-portal-principal.sql'),'utf8');
assert(router.includes("'/brand-portal/status'"));
assert(router.includes("'/brand-portal/oauth/start'"));
assert(router.includes("'/brand-portal/oauth/callback'"));
assert(router.includes('ROLE_SUPER_ADMIN'));
assert(server.includes('new BrandPortalOAuthService({ pool })'));
assert(html.includes('id="storeBrandPortalAction"'));
assert(app.includes('renderBrandPortalAction'));
assert(app.includes('需配置 Brand Portal App'));
assert(app.includes('/brand-portal/oauth/start?shop_id='));
assert(schema.includes("app_role IN ('ADS','BRAND_PORTAL')"));
console.log('Brand Portal UI/OAuth route contract: ok');
