const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.join(__dirname,'..');
const router=fs.readFileSync(path.join(root,'src','http-router.js'),'utf8');
const server=fs.readFileSync(path.join(root,'src','standalone-server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'web','index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'web','app.js'),'utf8');
const schema=fs.readFileSync(path.join(root,'schema-brand-portal-principal.sql'),'utf8');
const example=fs.readFileSync(path.join(root,'deploy','desktop','runtime.env.example'),'utf8');
assert(router.includes("'/erp/status'"));
assert(router.includes("'/erp/oauth/start'"));
assert(router.includes("'/erp/oauth/callback'"));
assert(router.includes('erpOAuthService'));
assert(server.includes('new ErpOAuthService({ pool })'));
assert(html.includes('id="storeErpAction"'));
assert(app.includes('renderErpAction'));
assert(app.includes('需配置 ERP App'));
assert(app.includes('/erp/oauth/start?shop_id='));
assert(schema.includes("app_role IN ('ADS','ERP','BRAND_PORTAL')"));
assert(example.includes('SHOPEE_ERP_REDIRECT_URL='));
console.log('ERP UI/OAuth route contract: ok');
