'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = rel => fs.readFileSync(path.join(__dirname, '..', rel), 'utf8');

const server = read('src/standalone-server.js');
const router = read('src/manual-data-sync-router.js');
const backfill = read('src/backfill-runner.js');
const index = read('web/index.html');
const app = read('web/app.js');
const productCard = read('web/product-card-ui-v2.js');
const coverage = read('web/product-card-coverage-v4.js');
const picker = read('web/date-range-picker-v2.js');
const httpRouter = read('src/http-router.js');

assert(server.includes("createManualDataSyncRouter({ pool })"));
assert(router.includes("router.post('/data/sync-range'"));
assert(router.includes("router.post('/data/sync-jobs'"));
assert(router.includes("router.get('/data/sync-jobs/:jobId'"));
assert(router.includes('forceRefresh: true'));
assert(router.includes('全店推历史数据（Campaign #'));
assert(backfill.includes('resume = true'));
assert(backfill.includes('resume: !forceRefresh'));
assert(backfill.includes("type: 'chunk-complete'"));
assert(index.includes('id="loadBtn" class="primary" type="button">读取数据</button>'));
assert(app.includes("postJson('/api/shopee-analytics/data/sync-jobs'"));
assert(app.includes("/api/shopee-analytics/data/sync-jobs/${encodeURIComponent(jobId)}"));
assert(app.includes('正在读取数据 ${percent}%'));
assert(app.includes('失败日期：'));
assert(app.includes('影响：仅 Shop+ Ads / 全店推'));
assert(app.includes("sources: ['product-ads', 'gms']"));
assert(app.includes("$('#loadBtn').addEventListener('click', readSelectedData)"));
assert(coverage.includes('缺失日期：'));
assert(coverage.includes('【读取数据】'));
assert(!picker.includes('disabled='), 'calendar must not disable days based on stored data');
assert(picker.includes('data-range-day="${iso}"'), 'calendar must render selectable calendar days');
assert(productCard.includes('data-generate-skill-analysis'));
assert(productCard.includes('/skill-report?shop_id=${ctx.shopId}'));
assert(productCard.includes("reason: 'MANUAL_UI'"));
assert(productCard.includes('data-generate-ad-group-skill'));
assert(productCard.includes('/ad-groups/skill-report?shop_id=${ctx.shopId}'));
assert(httpRouter.includes("router.post('/ad-groups/skill-report'"));
assert(picker.includes('draftStart = value;\n      draftEnd = value;\n      awaitingRangeEnd = true;'), 'first calendar click must form a valid single-day range');
assert(picker.includes('已选单日；可直接应用'), 'single-day selection must be visible to the user');
assert(!productCard.includes("$('#loadBtn')?.addEventListener('click'"), 'Product Card must not race the manual API sync button');
assert(picker.includes("shopee-date-range-changed"), 'picker must emit committed date changes');
assert(picker.includes("shopee-date-range-sync"), 'picker must resync after restored UI state');
assert(app.includes("window.dispatchEvent(new CustomEvent('shopee-date-range-sync'))"), 'restored date state must refresh picker text/calendar');
assert(productCard.includes("shopee-date-range-changed"), 'ads view must refresh after date selection');
assert(coverage.includes("shopee-date-range-changed"), 'coverage warning must refresh after date selection');
console.log('manual date-range data sync and Skill UI contract: ok');
