'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = rel => fs.readFileSync(path.join(__dirname, '..', rel), 'utf8');

const ui = read('web/product-card-ui-v2.js');
const index = read('web/index.html');
const repo = read('src/ad-promotion-repository.js');
const server = read('src/standalone-server.js');
const syncRunner = read('src/shop-sync-runner.js');
const channels = read('web/ad-channel-ui-v3.js');

for (const label of ['Product Card', '单品广告', '广告组', '全店推']) assert(ui.includes(label));
for (const type of ['manual', 'groups', 'auto']) assert(index.includes(`data-ads-type="${type}"`));
assert(!index.includes('data-ads-type="gmvmax"'));
assert(!index.includes('data-ads-type="gms"'));
assert(ui.includes('/api/shopee-analytics/product-ads/overview'));
assert(ui.includes('/api/shopee-analytics/product-ads?${params}'));
assert(ui.includes('/api/shopee-analytics/campaigns?${params}'));
assert(ui.includes('/api/shopee-analytics/campaigns/${campaignId}/analysis?${params}'));
for (const key of ['addToCartRate','costPerConversion','directItemsSold','directAcos','voucherAmount','voucheredSales']) assert(ui.includes(key), `missing metric ${key}`);
for (const key of ['impressions','clicks','ctr','conversions','itemsSold','gmv','expense','roas','voucherAmount','voucheredSales','addToCart','addToCartRate']) assert(ui.includes(`'${key}'`), `overview metric key missing ${key}`);
for (const token of ['comparisonRange','metric-change','metricTd','previousData']) assert(ui.includes(token), `comparison contract missing ${token}`);
assert(channels.includes("channelTabs.insertAdjacentElement('afterend', overviewPanel)"), 'overview must sit below the top-level ad-channel row');
assert(!ui.includes('data-ad-group-detail-index'), 'Ad Group items must no longer expand inline');
assert(ui.includes('product-card-detail-modal-backdrop'), 'shared detail modal shell must exist');
assert(ui.includes("variant: 'group'"), 'Ad Group detail must use the shared modal');
assert(ui.includes("title: '单品广告明细'"), 'single-product ad detail must use the shared modal');
assert(ui.includes("#manualAdDetail{display:none!important}"), 'legacy inline single-product detail must stay hidden');
assert(ui.includes('data-sort-group'), 'Ad Group parent row sort metadata must remain');
assert(!ui.includes('adGroupItemRowsV2'), 'separate Ad Group item panel must be removed');
assert(ui.includes("metricCol('sequence'),metricCol('dataDateSystem')"), 'Ad Group parent columns must follow Shopee export order with explicit system-added date');
assert(ui.includes("<th>${sl('sequence')}</th><th>${sl('adProductName')}</th><th>${sl('productId')}</th>"), 'Ad Group item detail must begin with Shopee Sequence / Ad Product Name / Product ID');
assert(index.includes('Shopee Ad Group 导出字段顺序'), 'Ad Group panel must explain export-aligned columns');
for (const token of ['sequence: sourceMetric(parent, \'Sequence\')','sequence: sourceMetric(child, \'Sequence\')','directConversions','costPerDirectConversion','voucherAmount','voucheredSales']) assert(repo.includes(token), `read model missing ${token}`);
assert(server.includes('/table-sort-v1.js'), 'global Shopee table sorter must be loaded');
assert(syncRunner.includes("adTypes: ['manual']"));
assert(syncRunner.includes("includeSettings: mode === 'daily'"));
assert(ui.includes("await loadProductAdDetailV2('auto', firstCampaignId"), 'shop-wide GMS detail must auto-load the first campaign');
assert(!ui.includes('点击一个全店推 Campaign 查看诊断'), 'shop-wide view must not require a manual detail click');
console.log('Product Card metrics, modal detail UX and source mapping contract: ok');
